# Generated by Django 2.0 on 2017-12-17 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('group_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'group_members',
            },
        ),
        migrations.CreateModel(
            name='GroupReview',
            fields=[
                ('group_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('agreed', models.IntegerField(default=0)),
                ('disagreed', models.IntegerField(default=0)),
                ('group_id', models.IntegerField()),
                ('agreed_percent', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'group_reviews',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=240)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='review_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='website.User'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='website.User'),
        ),
        migrations.AddField(
            model_name='groupreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Review'),
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='website.User'),
        ),
    ]
