# Generated by Django 2.0 on 2017-12-16 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=15)),
                ('text', models.CharField(max_length=240)),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='review',
            name='review_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='website.User'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='website.User'),
        ),
    ]
